### PR TITLE
Issue 12/unicode strings in predicate pushdown

### PR DESCRIPTION
**Pull request by jpizagno**
Includes new columns in Exasol Table called "UNICODE_COL" which inserts umlauts and direct unicode characters. Tests are also changed, it:test and test are both green.

### CODE REVIEW

**Comment by jpizagno** [comment]
@morazow 
Is the column name "UNICODE_COL" ok?
Do we need to test for characters (chinese characters)?

**Comment by morazow** [comment]
hey @jpizagno,

Thanks for working on this! 

Could you please also update `FiltersSuite.scala` test file [here](https://github.com/exasol/spark-exasol-connector/blob/master/src/test/scala/com/exasol/spark/util/FiltersSuite.scala#L90-L91). These should test that unicode chars from Spark are also compared to Exasol columns correctly.

**Comment by jpizagno** [comment]
Hello @morazow  So added tests for unicode and single-quotes in FiltersSuite.scala.  Let me know if you have more comments?
thanks
Jim

**Comment by morazow** [comment]
Hey @jpizagno,

This look good! I am going to merge it soon.

Thanks for your efforts getting this done!

**Pull request merged**
