### PR TITLE
Task/#44 bug spark decimal type to exasol decimal type

### PR DESCRIPTION
**Pull request by jpizagno**
@morazow @3cham 
An intitial PR.  Please review.  Maybe we need more tests?

### CODE REVIEW

**Comment by morazow** [comment]
Hey @jpizagno,

This looks great! 

I am going to merge this tonight or tomorrow morning (let's also wait for @3cham review). However, we can have a follow up tasks for adding an integration test, for example, save a decimal types and read back from Exasol.

Thanks for working on this task!

**Comment by 3cham** [comment]
Hi @jpizagno and @jpizagno: at first glance this looks good to me. However, I don't know if it is better when we change a bit and reuse the boundedDecimal [function](https://github.com/exasol/spark-exasol-connector/blob/01d63c7bb4f7f8ffdc29840aea860bdc77b9a236/src/main/scala/com/exasol/spark/util/Types.scala#L124-L128)

to something like:
`
DecimalType(
      math.min(math.min(precision, DecimalType.MAX_PRECISION), MAX_PRECISION_EXASOL)
      math.min(math.min(scale, DecimalType.MAX_SCALE), MAX_SCALE_EXASOL)
    )
`

and change the convertSparkPrecisionScaleToExasol function to:
`
    val boundedType = boundedDecimal(decimalType.precision, decimalType.scale)
    "DECIMAL(" + boundedType.precision.toString + "," + boundedType.scale.toString + ")"
`

IMO this avoids double code and we could just forget about the comparison between exasol & spark decimal type in the future. Let me know if you have other ideas :)

**Comment by morazow** [comment]
Good morning @3cham,

Thanks, great suggestions!

**Comment by jpizagno** [comment]
@morazow @3cham 
Great!  No problem.  Let me update the  convertSparkPrecisionScaleToExasol() function to use boundedDecimal, add an integration test, and update the PR.  I will try to do so today/tomorrow.

**Comment by jpizagno** [comment]
@morazow   (cc @3cham )   
  I have looked again, and I am not sure if using boundedDecimal() is correct.  boundedDecimal() sets the **max Spark** DecimalType.MAX* = **36**, whereas in convertSparkPrecisionScaletoExasol() we are looking for the **max Exasol** DecimalType = **38**.  So I think convertSparkPrecisionScaletoExasol() cannot use boundDecimal(). 
So as a concrete question and check, is the max Exasol Decimaltype 36 or 38 ?

However, following @3cham 's idea for refactoring, we could put those functions after each other in the code Types.scala, and also rename them appropriately:

boundedDecimal  -> boundedSparkDecimalType
convertSparkPrecisionScaletoExasol -> boundedExasolDecimalType

Then I think those 2 methods will be easier to read and compare/contrast or?

**Comment by morazow** [comment]
Hey @jpizagno,

It is other way round. 
- Maximum possible precision for Spark Decimal type is **38**
- Maximum possible precision for Exasol Decimal type is **36**

Taking minimum (bounding) of two as Tung suggested should be okay, since when reading (or writing) the precision value should not be more than 36 Exasol maximum value.

**Comment by 3cham** [comment]
Hi James,

the idea is to always use the minimum of precision and scale values (between Spark and EXASOL)  so that if those decimal types got updated in the future, we just change the constants and our read/write conversion would be safe. This requires the boundedDecimal function needs to take MAX_PRECISION_EXASOL & MAX_SCALE_EXASOL into account, something similar to:

```
  private[this] def boundedDecimal(precision: Int, scale: Int): DecimalType =
    DecimalType(
      math.min(math.min(precision, DecimalType.MAX_PRECISION), MAX_PRECISION_EXASOL),
      math.min(math.min(scale, DecimalType.MAX_SCALE), MAX_SCALE_EXASOL)
    )

```
Note that this function is originally used for converting data types from SQL ResultSet, so this change would be our double-check ;)

**Comment by jpizagno** [comment]
@morazow  @3cham 
Ok. no problems. I used the Code from @3cham , and the unittests and a manual test are positive. 

Do we need an IT test?

Do you want me to squash this commit and update/resubmit a PR?

manuel Test in Spark-shell 2.1.1
```
shell% spark-shell --jars ./target/scala-2.11/spark-exasol-connector-assembly-0.1.2-50-gcef9703-SNAPSHOT.jar
...
scala> val df = spark.sql("SELECT 1 AS A_INT, CAST(1.11 as DECIMAL(5,2)) AS A_DECIMALE")

scala> df
    .write
    .option("host","10.29.7.11..43")
    .option("port","8563")
    .option("table","OV_AS_ACCESS_LAB.JPIZAGNO_DELETEME")
    .option("username","jpizagno")
    .option("password","...")
    .format("exasol")
    .option("create_table","true")
    .save()
```

then in Exasol I see
```
CREATE TABLE JPIZAGNO_DELETEME (
    A_INT      DECIMAL(18,0) NOT NULL ENABLE,
    A_DECIMALE DECIMAL(5,2)
);
```
So DECIMAL(5,2) looks correct

then in Spark-shell 2.1.1
```
scala> val exasolQueryString = "SELECT A_INT, A_DECIMALE FROM OV_AS_ACCESS_LAB.JPIZAGNO_DELETEME"

scala> val df_read = spark
     .read
     .format("exasol")
     .option("host", "10.29.7.11..43")
     .option("port", "8563")
     .option("username", "jpizagno")
     .option("password", "...")
     .option("query", exasolQueryString)
     .load()
	 
scala> df_read.printSchema

root
 |-- A_INT: long (nullable = true)
 |-- A_DECIMALE: decimal(5,2) (nullable = true)

```

**Comment by morazow** [comment]
Hey all,

This looks good! I am going to merge (with squash) this pull request.

Thanks a lot for working on this issue!

FYI, I am going to request you to review short pull requests soon.

**Pull request merged**
